### ISSUE TITLE
bro could you please add the sql file ? for database 

### ISSUE THREAD

**Issue by 4riful** [sreejithkm001/JobPortalManagementSystem#1]

**Comment by sreejithkm001** [comment]
its already in the repository as JobPortalDb.bak file. MS SQl server i used.

**Comment by 4riful** [comment]
But bro the file is encrypted could you please upload the jobportaldb.sql , and can I connect with your twitter WhatsApp or Facebook which one do you prefer please?

**Comment by sreejithkm001** [comment]
.sql file not available. I used Microsoft SQL server Management studio.

**Comment by 4riful** [comment]
bro can I have the srcipt for the Microsoft SQL server Management studio so that I can create the database and tables

**Comment by sreejithkm001** [comment]
https://youtu.be/kQs0Uywl4_c?si=vqHntkbJvquI6mzz.
currently Project is not available in my system.Refer the utube video mentioned in repository description
